pipeline {
  agent any
  parameters {
        string(name: 'name_container', defaultValue: 'proyecto-qa', description: 'nombre del docker')
        string(name: 'name_imagen', defaultValue: 'iproyecto-qa', description: 'nombre de la imagen')
        string(name: 'tag_imagen', defaultValue: 'latest', description: 'etiqueta de la imagen')
        string(name: 'puerto_imagen', defaultValue: '81', description: 'puerto a publicar')
   }
   environment {
        name_final = '%name_container%%tag_imagen%%puerto_imagen%' 
   }
   stages {
        stage('init'){
          steps{
            script{
              bat 'echo %name_container%' 
              bat 'docker ps -f name=%name_container% -q | xargs --no-run-if-empty docker container stop'
              bat 'docker container ls -a -fname=%name_container% -q | xargs -r docker container rm'
            }
          }
          
       }

      
           
        stage('build') {
            steps {
                script{
                    bat ''' 
                    docker build -t %name_imagen%:%tag_imagen% ./docker_lab
                    '''
                    }
                    
                }                    
                                  
            }
            stage('run') {
            steps {
                script{
                    bat ''' 
                        docker run -dp %puerto_imagen%:80 --name %name_container% %name_imagen%:%tag_imagen%
 
                    '''
                    }
                    
                }                    
                                  
            }
            
          
        }   
    }
